services:
  - type: web
    name: event-feedback-analyzer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Event_Feedback_analyzer.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False