services:
  - type: web
    name: Event_Feedback_analyzer
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn Event_Feedback_analyzer.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: event_feedback_analyzer.settings
      - key: DATABASE_URL
        fromDatabase:
          name: event-feedback-db
          property: connectionString